
-- table drugbox
DROP TABLE drugbox IF EXISTS;
CREATE TABLE drugbox (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        dayly_intake FLOAT(22),
        inventory_amount FLOAT(22),
        inventory_date DATE,
        drug_id INT NOT NULL,
        patient_id INT NOT NULL
);
--CREATE unique index dbi_drug_patient ON drugbox (patient_id, drug_id);

-- table drugs
DROP TABLE drugs IF EXISTS;
CREATE TABLE drugs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        name VARCHAR(80) NOT NULL ,
        package_size INT,
        pzn VARCHAR(8)
);
CREATE INDEX drugs_name ON drugs (name);

-- table patients
DROP TABLE patients IF EXISTS;
CREATE TABLE patients (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        first_name VARCHAR(255) NOT NULL ,
        last_name VARCHAR(255) NOT NULL ,
        city VARCHAR(255) DEFAULT NULL,
        house_number VARCHAR(255) DEFAULT NULL,
        street VARCHAR(255) DEFAULT NULL,
        zip VARCHAR(255) DEFAULT NULL,
        telephone VARCHAR(255) DEFAULT NULL
);
